name: build edurogue images

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Read version from file
        id: read_version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: |
          docker buildx build \
          --tag vbarahona/edurogue:${{ steps.read_version.outputs.version }} \
          --tag vbarahona/edurogue:latest \
          --platform linux/amd64,linux/arm64 .
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
          --tag vbarahona/edurogue:${{ steps.read_version.outputs.version }} \
          --tag your-username/multiarch-example:latest \
          --platform linux/amd64,linux/arm64 .